CREATE OR REPLACE DATABASE PETS;
CREATE OR REPLACE SCHEMA PETS.PETS_SCHEMA;

CREATE STAGE PETS.PETS_SCHEMA.PETS_STAGE
  URL='s3://snowflake-dbt-hands-on/'
  file_format = (type = 'JSON');

SELECT 
t.$1
FROM @PETS.PETS_SCHEMA.PETS_STAGE t;

CREATE OR REPLACE TABLE PETS.PETS_SCHEMA.PETS (
  LASTNAME STRING,
  AGE INT,
  HOBBIE STRING,
  PET_NAME STRING,
  PET_TYPE STRING
);

COPY INTO PETS.PETS_SCHEMA.PETS
FROM (
  SELECT 
    t.$1:name.last::STRING,
    t.$1:age::NUMBER,
    t.$1:hobbies[0]::STRING,
    t.$1:pet.name::STRING,
    t.$1:pet.type::STRING
  FROM @PETS.PETS_SCHEMA.PETS_STAGE t
);

SELECT * FROM PETS.PETS_SCHEMA.PETS;